In [1]:
import torch

In [2]:
# import numpy as np
import matplotlib.pyplot as plt

In [3]:
from map_class import MapClass
from graph_class import Graph

In [4]:
#Training inputs for RGBcolors
rgb_colors = [[0., 0., 0.],
      [0., 0., 1.],
      [0., 0., 0.5],
      [0.125, 0.529, 1.0],
      [0.33, 0.4, 0.67],
      [0.6, 0.5, 1.0],
      [0., 1., 0.],
      [1., 0., 0.],
      [0., 1., 1.],
      [1., 0., 1.],
      [1., 1., 0.],
      [1., 1., 1.],
      [.33, .33, .33],
      [.5, .5, .5],
      [.66, .66, .66]]

In [5]:
rgb_lables = \
    ['black', 'blue', 'darkblue', 'skyblue',
     'greyblue', 'lilac', 'green', 'red',
     'cyan', 'violet', 'yellow', 'white',
     'darkgrey', 'mediumgrey', 'lightgrey']

In [6]:
# Network configuration

data = rgb_colors
data_lables = rgb_lables
batch_size = 2


sigma = None

# for now amount_verticies has to be a multiplication of length and width
length = 10
width = 10
number_epochs = 100
shuffle = True

learning_rate = 0.01

In [7]:
#buildings data
building_sizes = [[0.1, 0.3], [0.1, 0.2], [1., 1.], [0.125, 0.2], [0.529, 0.12], [1.0, 0.3], [0.33, 0.3], 
                  [0.4, 0.4], [0.67, 0.3], [.33, 0.7], [.5, 0.1]]

In [8]:
building_labels = building_sizes

In [9]:
#Training inputs for RGBcolors
gray_colors = [[0.1], [0.], [1.], [0.125], [0.529], [0.9], [0.33], [0.4], [0.67], [.33], [.5]]

In [10]:
gray_colors_lables = [[0.1], ["black"], ["white"], [0.125], [0.529], [0.9], [0.33], [0.4], [0.67], [.33], [.5]]

In [11]:
# Graph setup

In [12]:
# for now amount_verticies has to be a multiplication of length and width
amount_nodes = 100
percent_edges = 0.5

In [13]:
# using graph class to generate matrix

graph1 = Graph()

In [14]:
# matrix genaration

matrix1 = graph1.create_matrix(amount_nodes)
edges1 = graph1.generate_edges(amount_nodes, percent_edges)
matrix1 = graph1.add_edges(matrix1, edges1)

5000


In [15]:
# matrix2 = graph1.standard_som_distance_matrix(4, 3)
# matrix2

In [16]:
map1 = MapClass(data, length, width, learning_rate, number_epochs, matrix1, sigma, data_lables, batch_size, shuffle)

3
15
tensor([[0.7027, 0.6533, 0.3505],
        [0.5522, 0.6536, 0.8551],
        [0.8603, 0.8914, 0.7444],
        [0.6234, 0.2025, 0.3854],
        [0.2282, 0.9639, 0.2934]])
tensor([[0.7027, 0.6533, 0.3505],
        [0.5522, 0.6536, 0.8551],
        [0.8603, 0.8914, 0.7444],
        [0.6234, 0.2025, 0.3854],
        [0.2282, 0.9639, 0.2934]])


In [17]:
# drawtype="rbg" tries to draw colors on map - needs an input data with 3 vectors

# drawtype="black-white" draws black-white
# drawtype="None" - default draws empty space

# labels=True or False draws labels on the map... labels are necessary...
labels=True

drawtype = "rbg"

# draw_every_epoch=0 Don't draw anything
# draw_every_epoch=10 draw every 10 epochs


plt.rcParams['figure.dpi'] = 150
map1.large_cycle(draw_every_epoch=100, drawtype=drawtype)

In [18]:
map1.history[0][0:5]

tensor([[0.7027, 0.6533, 0.3505],
        [0.5522, 0.6536, 0.8551],
        [0.8603, 0.8914, 0.7444],
        [0.6234, 0.2025, 0.3854],
        [0.2282, 0.9639, 0.2934]])

In [20]:
map1.history[1][0:5]

tensor([[0.3922, 0.3912, 0.2965],
        [0.4985, 0.4267, 0.4828],
        [0.4932, 0.5622, 0.6348],
        [0.3669, 0.4329, 0.6208],
        [0.4107, 0.5791, 0.4649]])

In [ ]:
map1.draw_all(drawtype, labels=labels)

In [ ]:
list_edges = graph1.make_list_edges_distances(matrix1)
# list_edges

In [ ]:
netxgraph1 = graph1.build_networkx_graph(list_edges)

In [ ]:
map1.visualize_networkx(netxgraph1)